# Generated by Django 2.0.3 on 2018-03-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='home_page',
            field=models.URLField(max_length=100),
        ),
    ]
