# Generated by Django 2.0.3 on 2018-03-09 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20180308_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(null=True)),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('short_position_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='short_team_name',
            field=models.CharField(default='???', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membership',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Player'),
        ),
        migrations.AddField(
            model_name='membership',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Position'),
        ),
        migrations.AddField(
            model_name='membership',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(through='teams.Membership', to='teams.Player'),
        ),
    ]
