# Generated by Django 2.0.3 on 2018-03-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20180309_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='date_left',
            field=models.DateField(blank=True, null=True),
        ),
    ]
